### ISSUE TITLE
Order and analysis of components

### ISSUE THREAD

**Issue by mikeshams** [sharmaronak79/Capstone-project-summer2020#1]

**Comment by mikeshams** [comment]
[Group7-Assignment5_new.pptx](https://github.com/sharmaronak79/Capstone-project-summer2020/files/4853749/Group7-Assignment5_new.pptx)
Explain why you decided to choose LPC 2148!

**Comment by mikeshams** [comment]
GSM Module, Pulse Rate sensor, and Lithium Battery are not available!

**Comment by sharmaronak79** [comment]
we got all components sir

**Comment by mikeshams** [comment]
What are purposes to use ESP 32?

**Comment by sharmaronak79** [comment]
because it has inbuilt wifi and camera , which is very useful ,as it requires less space and as per our requirement it is very reliable to upload image on server
