### ISSUE TITLE
Schematic design

### ISSUE THREAD

**Issue by mikeshams** [sharmaronak79/Capstone-project-summer2020#2]

**Comment by mikeshams** [comment]
1. What issues did you face or others might face with working with Proteus ISIS?
2. Compare Proteus with Easy EDA?
3. Did you install Proteus for Windows or Linux? What's the download link?

**Comment by Amandeepkaur786** [comment]
1. steps :i face a problem that i could not find library of esp32-cam.
then 1. i go to 2d graphics box mode to make ic box.
2. click on device pin modes to make pins.then edit the pins with required pins number and pin function.
3.after that  i selected whole ic .the i go to libraries to make my devices.
4.there i give name to device and prefix.
5.then search in pick devices .it was there.




2. Most of data is available on proteus on internet and it makes my feel easy to learn.
In easy eda we have some time for free version,but proteus isis is totally free.


3.https://allpcworld.com/proteus-8-download/
