### ISSUE TITLE
Interfacing pulse rate sensor with LPC2148

### ISSUE THREAD

**Issue by mikeshams** [sharmaronak79/Capstone-project-summer2020#5]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of the heart rate sensor to the LPC in terms of Hardware and Software?

**Comment by shweta3109** [comment]
In terms of hardware,As square waves are better to proceed with,So while I was trying to convert the output of pulse rate sensor to square wave by using op-amp ,the low voltage was not exact zero.so,I used optocoupler(in which transistor is used as switch) and it resolved the issue.
In terms of software,I did not face any issue as there are many resources available on internet for this and with proper understanding of registers,coding can be done and it works
