### ISSUE TITLE
Interfacing GPS with LPC2148

### ISSUE THREAD

**Issue by mikeshams** [sharmaronak79/Capstone-project-summer2020#6]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of a GPS module to the LPC2148 in terms of Hardware and Software?
2. How did you solve them?

**Comment by shweta3109** [comment]
In case of Hardware,I did not face any problem as there are just 4 pins to be connected that are Rx,Tx,Vcc and Ground.So,it was easy to interface.
In case of Software, I found some difficulty to understand the code as the use of flags were there.Then I searched about it and came to know that they were used to check different conditions at different time.
Also the code was a bit long,so I defined the functions related to UART in a separate file that is serial.c and declared in serial.h.After that included serial.h in the main code as a library.
This way I was able to make coding somewhat short.
