### ISSUE TITLE
Interfacing ESP32 CAM  to LPC2148

### ISSUE THREAD

**Issue by mikeshams** [sharmaronak79/Capstone-project-summer2020#7]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of an ESP 32 CAM to the LPC 2148 in terms of Hardware and software?
2. How do you solve them?

**Comment by Amandeepkaur786** [comment]
1. 
i.I face issue related arduino ide that that there there was no esp32 cam ai thinker model.
ii.arduino ide was not installed on my window 10.

2.i.Then we download esp in the board manger,then this camera module starts appear.
ii.then install arduino ide on linux. it works well with linux.
