### ISSUE TITLE
Interfacing GSM with LPC2148

### ISSUE THREAD

**Issue by mikeshams** [sharmaronak79/Capstone-project-summer2020#8]

**Comment by mikeshams** [comment]
1. What issues did you or others might face when connecting the GSM Module to the LPC?
2. How did you resolve them?

**Comment by sharmaronak79** [comment]
when I started my interfacing with GSM I had a problem with power supply and its ground terminal, 
sometimes there was an issue of serial communication. So, I gave power from the same supply and make a common ground of communication and power supply also.
